query getProblemDetail($titleSlug: String!) {
        question(titleSlug: $titleSlug) {
                questionFrontendId
                questionTitle # or title
                questionTitleSlug # or titleSlug
                questionType
                content
                difficulty
                categoryTitle
                metaData
                exampleTestcaseList
                stats
                similarQuestionList {
                        difficulty
                        titleSlug
                        isPaidOnly
                }
                topicTags {
                        name
                        slug
                        id
                }
                positionLevelTags {
                        name
                        slug
                }
                featuredContests {
                        title
                        titleSlug
                }
                codeSnippets {
                        lang
                        code
                }
                isPaidOnly
        }
}
