query getProblemDetail($titleSlug: String!) {
        question(titleSlug: $titleSlug) {
                # ---CORE---
                questionId
                questionFrontendId
                questionDetailUrl
                questionTitle # or title
                questionTitleSlug # or titleSlug
                translatedTitle
                questionType
                content
                translatedContent
                difficulty
                categoryTitle
                metaData

                # ---TESTCASES---
                exampleTestcaseList
                exampleTestcases
                sampleTestCase

                # ---AC STATS---
                stats
                acRate

                # ---SIMILAR QUESTIONS---
                similarQuestions
                similarQuestionList {
                        difficulty
                        titleSlug
                        title
                        translatedTitle
                        isPaidOnly
                }

                # ---TOPICS, POSITION, AND CONTEST---
                topicTags {
                        name
                        translatedName
                        slug
                        id
                }
                positionLevelTags {
                        name
                        nameTranslated
                        slug
                }
                featuredContests {
                        title
                        titleSlug
                }

                # ---COMPANY TAGS---
                companyTagStats
                companyTagStatsV2
                isPaidOnly

                # ---USER STATUS---
                status
                isLiked
                isFavor

                # ---PUBLIC OPINION---
                likes
                dislikes
                freqBar
                hide

                # ---CHALLENGES---
                nextChallenges {
                        questionId
                        questionFrontendId
                        title
                        titleSlug
                        difficulty
                }
                nextChallengePairs

                # ---HINTS AND SOLUTIONS---
                hints
                hasSolution
                hasVideoSolution
                solution {
                        id
                        title
                        content
                        contentTypeId
                        canSeeDetail
                        rating {
                                count
                        }
                }

                # ---CODE SNIPPETS---
                codeSnippets {
                        lang
                        langSlug
                        code
                }

                # ---JUDGE---
                judgerAvailable
                judgeType

                # ---ENVIRONMENT---
                canSeeQuestion
                envInfo
                enableTestMode
                enableRunCode
                enableSubmit
                enableDebugger

                # ---CONTRIBUTORS---
                contributors {
                        username
                        profileUrl
                }

                # ---OTHER---
                randomQuestionUrl
                mysqlSchemas
                dataSchemas
                frontendPreviews
                libraryUrl
                adminUrl
                hasFrontendPreview
        }
}
